ansible-collections/community.libvirt

galaxy.yml

Adds ansible-galaxy metadata
Fixes: #21
```paste below
```

Add Galaxy file

---

tests/integration/targets/connection_libvirt_lxc/aliases
tests/integration/targets/connection_libvirt_lxc/runme.sh
tests/integration/targets/connection_libvirt_lxc/test_connection.inventory

This is a migration of the community.general content as-is
with only the plugin path changed.
ref: https://github.com/ansible-collections/community.general/pull/180
```paste below
```

Add libvirt_lxc connection integration test

---

README.md
README.rst
galaxy.yml

While this is not entirely complete, it covers a bit more information
relevant to the new collection.
```paste below
```

Add more complete README

---

tests/utils/shippable/shippable.sh

Switch back to testing ansible-devel

---

plugins/connection/libvirt_qemu.py
tests/integration/targets/connection_libvirt_qemu/aliases
tests/integration/targets/connection_libvirt_qemu/runme.sh
tests/integration/targets/connection_libvirt_qemu/test_connection.inventory

Initial pass at libvirt/qemu connection plugin
Fixes: #12 
```paste below
```

Add generic libvirt connection plugin

---

plugins/modules/virt.py
plugins/modules/virt_net.py
plugins/modules/virt_pool.py
tests/sanity/ignore-2.10.txt

This fixes some missing types, aliases and choices.

Fix doc issues flagged by `ansible-test sanity`

---

plugins/connection/libvirt_qemu.py

Closes: #29
```paste below
```

Implement connection/libvirt_qemu remote URI support

---

plugins/connection/libvirt_qemu.py

The connection plugin will not work unless the right capabilities
are present for the VM's guest-agent. In this patch we add a test
to verify whether they are present and to raise an exception if
they are not.
Fixes: #34
```paste below
```

Implement connection/libvirt_qemu capabilities test

---

.gitignore
plugins/inventory/libvirt.py

This pull request adds the ability to set the ```inventory_hostname``` to the UUID for the domain
libvirt inventory plugin

Option inventory hostname

---

plugins/connection/libvirt_qemu.py

This adds windows support to ```community.libvirt.libvirt_qemu```
```community.libvirt.libvirt_qemu``` connection plugin

Add Windows support to libvirt_qemu

---

.azure-pipelines/azure-pipelines.yml
README.md
shippable.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt
tests/utils/shippable/check_matrix.py
tests/utils/shippable/shippable.sh
tests/utils/shippable/units.sh

* Bring `shippable.sh` inline with other repos
* Add AZP and codecoverage badge

Normalise shippable.sh

---

galaxy.yml
plugins/connection/libvirt_qemu.py
plugins/inventory/libvirt.py

libvirt_qemu plugin: add import error handling
plugins/connection/libvirt_qemu.py

libvirt_qemu plugin: add import error handling

---

.azure-pipelines/azure-pipelines.yml

https://github.com/ansible-collections/overview/issues/45#issuecomment-776859063
Relaunch tests and merge after https://github.com/ansible-collections/community.libvirt/pull/59
.azure-pipelines/azure-pipelines.yml

azure-pipelines: update test matrix

---

.azure-pipelines/azure-pipelines.yml

https://github.com/ansible-collections/overview/issues/45#issuecomment-776163864
Relaunch tests and merge after https://github.com/ansible-collections/community.libvirt/pull/59
- 
.azure-pipelines/azure-pipelines.yml

Update Azure pipelines test container 1.7.1 -> 1.8.0

---

plugins/connection/libvirt_qemu.py

Once the `libvirt_qemu` connection plugin has spawned a command via the qemu guest agent, it needs to wait for it to finish.
This is done in an active wait loop.
However, without any sleep, this wait loop consumes a lot of CPU.
On my machine, the following command:
```
ansible archlinux-vm -m command -a "sleep 10"
```
makes the `qemu-ga` of my VM consume 20% of CPU and `systemd-journald` consume 7% of CPU because all qemu guest agent commands are logged.
Adding a fixed value sleep time in each loop iteration could make tasks execution run slower, especially if there are a lot of quick ones.
In order to not constantly consume a CPU for long-running tasks without increasing the latency on quick ones, this change introduces an exponentially increasing sleep in the active wait loop.
It …

connection/libvirt_qemu: Mitigate a CPU hammering active wait loop

---

tests/sanity/ignore-2.12.txt

Relates to failings in https://github.com/ansible-collections/community.libvirt/pull/68 and https://github.com/ansible-collections/community.libvirt/pull/67

Fix sanity failings

---

CONTRIBUTING.md
MAINTAINING.md
REVIEW_CHECKLIST.md

Add CONTRIBUTING.md, MAINTAINING.md, and REVIEW_CHECKLIST.md

Add CONTRIBUTING.md, MAINTAINING.md, and REVIEW_CHECKLIST.md

---

plugins/inventory/libvirt.py

https://github.com/ansible-collections/community.libvirt/pull/73
`plugins/inventory/libvirt.py`

Fix inventory plugin

---

changelogs/fragments/73-plugin-name-fqcn.yaml

Fix changelog fragment
i think NO REVIEW NEEDED

Fix changelog fragment

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/73-plugin-name-fqcn.yaml
galaxy.yml

Release 1.0.2 commit

---

galaxy.yml

Fix doc reference in galaxy.yml, update version to the next expected

Fix doc reference in galaxy.yml, update version to the next expected

---

tests/sanity/ignore-2.13.txt
tests/unit/mock/loader.py

Relates to https://github.com/ansible-collections/overview/issues/45#issuecomment-926794724

Copy ignore-2.12.txt to ignore-2.13.txt

---

.azure-pipelines/azure-pipelines.yml

Relates to https://github.com/ansible-collections/overview/issues/45#issuecomment-963553255

AZP: change Fedora 33 to Fedora 35 when testing against devel

---

.azure-pipelines/azure-pipelines.yml

CI: update AZP matrix

---

MAINTAINERS

https://github.com/ansible-collections/community.libvirt/issues/78#issuecomment-978461658

MAINTAINERS: Add new maintainer

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/114_replace_distutils_spawn.yml
changelogs/fragments/90_add_integration_test_for_virt_pool.yml

Release for 1.1.0.
Fixes #119 (I hope)

Release 1.1.0 commit

---

galaxy.yml

Now that `1.1.0` is out, update galaxy for next expected release.

Update galaxy to next expected release

---

.azure-pipelines/azure-pipelines.yml

See https://github.com/ansible-collections/news-for-maintainers/issues/18

CI: update Azure test container

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/108_make_virt_net_modify_idempotent.yml
changelogs/fragments/113_extra_inventory_info.yml
changelogs/fragments/virt_pool_no_path.yml
galaxy.yml

Release 1.2.0 commit

---

CONTRIBUTING.md
REVIEW_CHECKLIST.md

Combine REVIEW_CHECKLIST.md and CONTRIBUTING.md and fix links
meta

Combine REVIEW_CHECKLIST.md and CONTRIBUTING.md and fix links

---

.azure-pipelines/azure-pipelines.yml
tests/sanity/ignore-2.15.txt

CI: add 2.14 tests, ignore-2.15 to avoid CI failing

---

.azure-pipelines/azure-pipelines.yml

Update devel CI pipline
See https://github.com/ansible-collections/news-for-maintainers/issues/31

CI: update OS versions for devel

---

.azure-pipelines/azure-pipelines.yml
tests/sanity/ignore-2.16.txt

Add tests against upstream stable 2.15
https://github.com/ansible-collections/news-for-maintainers/issues/41

Ci stable 215

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/134_virt_pool_replace_functions_listStoragePools.yml
changelogs/fragments/135_virt_pool_replace_function_listVolumes.yml
changelogs/fragments/136_fix_undefine_nvram.yml
changelogs/fragments/142_virt_define_improvements.yml
changelogs/fragments/147_fix_qemu_remote_target_warning.yml
changelogs/fragments/156_fix_windows_encoding.yml
galaxy.yml

Release 1.3.0 commit

---

.azure-pipelines/azure-pipelines.yml

See https://github.com/ansible-collections/news-for-maintainers/issues/71

ci: update test container to 6.0.0

---

README.md

README: remove old communication section

README: remove old communication section

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-readme.yml
changelogs/fragments/libvirt_lxc.yml

Release 1.3.1 commit

---

.azure-pipelines/azure-pipelines.yml

AZP matrix: remove stable-2.15 testing as EOL

AZP matrix: remove stable-2.15 testing

---

.azure-pipelines/azure-pipelines.yml

AZP: add 2.19, remove 2.16

---

.azure-pipelines/azure-pipelines.yml
plugins/modules/virt_volume.py
tests/sanity/ignore-2.20.txt

ansible-core’s devel and milestone branch versions have been bumped to 2.20.0.dev0, add ignore file.
Fixes #202

ci: devel is 2.20, add ignore file
