ansible-collections/community.libvirt

- plugins/modules/virt.py
The define action searches for the domain name into the xml definition to determine if the domain needs to be created or updated. The `xml` variable contains the parsed definition but doesn't guarantee the existence of the name tag. If there is not match to the given pattern the task fails without raising the proper error message.
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'groups'
```
virt module
```paste below
```
> Define command fails with invalid xml domain file

- changelogs/fragments/48-virt-detect-domain-update.yml
- plugins/modules/virt.py
When using command `define` with module `virt`, originally it checked whether the domain was updated by calling `XMLDesc()` on object representing the old domain and comparing it with the result of `XMLDesc()` called on the object representing the new domain. However, after update, both objects referenced the same domain, therefore both calls returned the same XML and the module never detected any change.
Now, `virt` module gets the original domain XML before updating it.
Also, `XMLDesc()` returns configuration of running domain, since we are updating persistent configuration, we must explicitly request XML of inactive domain, otherwise config change won't be detected if the domain is running.
virt
Tested on:
- Arch Linux, libvirt 6.5.0-3 (libvirt-python 6.9.0) with …
> virt: Return status changed when re-defining domain

- plugins/modules/virt_net.py
- tests/integration/targets/virt_net/tasks/main.yml
The name parameter is not required for the list_nets or facts
command so we adjust the module to allow for that.
Fixes #49
virt_net
```paste below
```
> virt_net: Make name parameter optional

- plugins/modules/virt.py
There is no 'message' property. Instead, there is a function
to fetch the message:
https://libvirt.org/docs/libvirt-appdev-guide-python/en-US/html/libvirt_application_development_guide_using_python-Error_Handling.html
Fixes #52
virt
```paste below
```
> [virt] Correctly get the error message

- changelogs/fragments/73-plugin-name-fqcn.yaml
- plugins/inventory/libvirt.py
Fix the `community.libvirt.libvirt` inventory plugin with the latest version of Ansible.
- `community.libvirt.libvirt` inventory plugin
I have an Ansible playbook that targets a `libvirt` VM.
Concretely, I have this in my `$ANSIBLE_CONFIG` file:
```ini
[defaults]
inventory = inventory-libvirt.yaml
[inventory]
enable_plugins = community.libvirt.libvirt
```
And my `inventory-libvirt.yaml` file contains:
```yaml
plugin: community.libvirt.libvirt
uri: 'qemu:///system'
```
This setup used to work but is now broken with this version:
```sh
$ ansible --version
ansible [core 2.11.1] 
$ ansible-galaxy collection list | grep libvirt
community.libvirt             1.0.1  
```
I know get the following error:
```sh
$ ANSIBLE_CONFIG=ansible-libvirt.cfg ansible-playbook -C -D …
```
> Fix `community.libvirt.libvirt` inventory plugin

- plugins/doc_fragments/virt.py
- plugins/modules/virt.py
- plugins/modules/virt_net.py
- plugins/modules/virt_pool.py
This moves the options for the virt.py module into doc_fragments and reuses them for virt_net and virt_pool.
This is to facilitate reuse and further developments of the modules, eg to split into per command modules (+_info  modules)
virt.py
```paste below
```
> Split of doc_fragments for virt options

- .azure-pipelines/azure-pipelines.yml
FreeBSD 12.2 is deprecated and needs to be replaced with 12.3 for Azure
pipelines running against the devel branch.
Relates to https://github.com/ansible-collections/overview/issues/45
Fixes #102
> CI: replace FreeBSD 12.2 with 12.3 for remote devel

- plugins/connection/libvirt_qemu.py
Windows guests are supported with the connection plugin, however in
order to trigger the required code path, the 'ansible_shell_type'
variable must be set to 'cmd' or 'powershell' for that host. Without
that, Ansible will default to `/bin/sh` which does not work.
This docs patch makes the requirements more clear.
Relates to #92 
connection plugin
> WIP: doc: clarify connection reqs for Windows guests

- .azure-pipelines/azure-pipelines.yml
- shippable.yml
CentOS 8 has been fully discontinued and mirrors are removing content.
This patch removes centos8 from the test matrix.
Relates to https://github.com/ansible-collections/news-for-maintainers/issues/3
- CI Pull Request
> CI: remove centos8 from test matrix

- changelogs/fragments/114_replace_distutils_spawn.yml
- plugins/connection/libvirt_lxc.py
- plugins/connection/libvirt_qemu.py
- plugins/inventory/libvirt.py
This PR also merges in the changes from #114.
It fixes two issues relating to failing pipelines
ansible-test's validate-modules sanity test was extended to also
validate the documentation (and thus configuration) for (documentable)
plugins. This introduced a schema which required updating of
documentation in order for the test to pass.
See https://github.com/ansible/ansible/pull/71734
See https://github.com/ansible-collections/news-for-maintainers/issues/9
Failing test:
```
$ ansible-test sanity --test validate-modules
Running sanity test "validate-modules"
ERROR: Found 9 validate-modules issue(s) which need to be resolved:
ERROR: plugins/connection/libvirt_lxc.py:0:0: invalid-documentation: DOCUMENTATION.author: Invalid author for dictionary value @ data['author']. Got ['Michael Scherer …
```
> Update doc elements to pass validate-modules test, remove usage of distutils.spawn

- tests/sanity/ignore-2.14.txt
The ansible-core devel branch has been updated to version 2.14.0. This
patch copies the 2.13 test ignore entries so that they will be ignored
for 2.14.
Relates to https://github.com/ansible-collections/news-for-maintainers/issues/13
> Add sanity test ignore entries for 2.14

- .azure-pipelines/azure-pipelines.yml
- tests/integration/targets/virt_net/vars/RedHat-9.yml
- tests/integration/targets/virt_pool/vars/RedHat-9.yml
This change removes the following from devel testing:
- Fedora 34
- FreeBSD 13.0
- RHEL 8.5
- Ubuntu 18.04
This change adds the following from devel testing:
- Fedora 36
- FreeBSD 13.1
- RHEL 8.6
- RHEL 9.0
- Ubuntu 22.04
See https://github.com/ansible-collections/news-for-maintainers/issues/17
> CI: update test envs for devel

- changelogs/fragments/virt_pool_no_path.yml
- plugins/modules/virt_pool.py
Fix for #129, allows target path to be an optional fact
virt_pool (facts)
```paste below
```
> Make path optional in virt_pool facts

- changelogs/fragments/134_virt_pool_replace_functions_listStoragePools.yml
- plugins/modules/virt_pool.py
According to the libvirt storage API reference, the functions
- listStoragePools (virConnectListStoragePools)
- listDefinedStoragePools (virConnectListDefinedStoragePools)
should not be used anymore: "The use of this function is discouraged.
Instead, use virConnectListAllStoragePools()" ... "This API solves the
race inherent between virConnectListStoragePools and
virConnectListDefinedStoragePools."
Source:
https://libvirt.org/html/libvirt-libvirt-storage.html#virConnectListAllStoragePools
Examples:
- get ALL  pools with listAllStoragePools()
- get active pools with listAllStoragePools(2)
- get inactive pools with listAllStoragePools(1)
The function "virConnectListAllStoragePools()" appeared in version
0.10.2 which was released in 2012. It seems rather unlikely that
somebody is still using …
> virt_pool: replace functions listStoragePools and listDefinedStoragePools

- changelogs/fragments/135_virt_pool_replace_function_listVolumes.yml
- plugins/modules/virt_pool.py
This PR is similar to #134.
According to the libvirt storage API reference, the function
- listVolumes (virStoragePoolListVolumes)
should not be used anymore: "The use of this
function is discouraged. Instead, use virStoragePoolListAllVolumes()."
Source:
https://libvirt.org/html/libvirt-libvirt-storage.html#virStoragePoolListVolumes
The function "virStoragePoolListAllVolumes()" appeared in version
0.10.2 which was released in 2012. It seems rather unlikely that
somebody is still using an older unsupported libvirt version, so the
risk should be rather low.
Source:
https://libvirt.org/hvsupport.html#virStorageDriver
libvirt_pool
My tests confirm that the bugfix works as expected. It does not change the output of virt_pool with facts and info compared to the old …
> Replace discouraged function listVolumes

- changelogs/fragments/136_fix_undefine_nvram.yml
- plugins/modules/virt.py
Fixes #40
Libvirt function `undefine()` is not able to delete nvram or other
metadata. Therefore it is replaced with `undefineFlags()` which is able to
handle it by using flags.
All possible flags are listed in 'ENTRY_UNDEFINE_FLAGS_MAP'. Integer 23
makes `undefine` successful in all cases (1 + 2 + 4 + 16).
Source:
https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainUndefineFlags
The flags `nvram`(4) and `keep_nvram`(8) are mutually exclusive.
To control the metadata handling during `undefine`, two new options
`force` and `flags` are introduced including documentation and examples.
The function `undefineFlags()` appeared in libvirt version 0.9.4 which was
release in 2011. It seems rather unlikely that somebody is still using
an older unsupported libvirt version. Additionally, if …
> Fix virt module to undefine a domain with nvram or other metadata

- .azure-pipelines/azure-pipelines.yml
- plugins/inventory/libvirt.py
Fedora 35 is deprecated from devel, this commit removes it from devel
and adds it to Docker 2_13 so that it continues to be tested.
> CI: remove f35 from devel

- plugins/modules/virt.py
- plugins/modules/virt_net.py
- plugins/modules/virt_pool.py
The Ansible Steering Committee voted to make all docs refer to booleans as true/false, as there is currently a mix of
yes/no/True/False/true/false.
See https://github.com/ansible-community/community-topics/issues/116
Fixes #139
> doc: set booleans to true/false for consistency

- changelogs/fragments/142_virt_define_improvements.yml
- plugins/doc_fragments/virt.py
- plugins/modules/virt.py
This pull request effectively rewrites how domains are defined.
To summarize its changes:
- Diff info is now supplied, showing the changes between previously and
newly defined domain XML.
- If a domain with the same name already exists and the incoming UUID is
missing, apply the existing UUID to the incoming XML.
- If a UUID is defined in the incoming XML and it doesn't match that of
an existing domain with the same name, exit with an error
- For any incoming XML <interface> missing a <mac> element, we will
attempt to fetch MAC of the matching interface from the existing
domain's XML
- Improvement Pull Request
virt
Before these changes, if a definition was given without a UUID, the
appropriate domain would be created with a libvirt-generated UUID. If
the definition was modified (with UUID …
> Virt define improvements

- changelogs/fragments/147_fix_qemu_remote_target_warning.yml
- plugins/connection/libvirt_qemu.py
Fixes a warning that appears on every task about the `community.libvirt.libvirt_qemu` connection plugin having an improperly configured remote target value.
```
[WARNING]: The "community.libvirt.libvirt_qemu" connection plugin has an improperly configured remote target value, forcing "inventory_hostname" templated value instead of the string
```
community.libvirt.libvirt_qemu
This fix is similar to the one found at [containers/ansible-podman-collections #506](https://github.com/containers/ansible-podman-collections/pull/506).
**Before:**
```
❯ ansible-playbook -i virt1_inventory.yml test.yml
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
PLAY [VM Main Playbook] …
```
> QEMU connection plugin warning: improperly configured remote target

- .azure-pipelines/azure-pipelines.yml
Deprecate RHEL 8.7 and 9.1 and add 8.8 and 9.2 to remote devel.
See https://github.com/ansible-collections/news-for-maintainers/issues/47
> CI: update RHEL for remote devel

- .azure-pipelines/azure-pipelines.yml
ansible-core devel is dropping controller support for Python 3.9, we need to update the base container to a newer version.
See https://github.com/ansible-collections/news-for-maintainers/issues/49
Fedora 37 is deprecated from the devel version of ansible-test, update this to Fedora 38.
See https://github.com/ansible-collections/news-for-maintainers/issues/50
FreeBSD 14.1 is deprecated from the devel version of ansible-test, removed.
See https://github.com/ansible-collections/news-for-maintainers/issues/53
> CI: update test container and update operating systems

- .azure-pipelines/azure-pipelines.yml
- tests/sanity/ignore-2.16.txt
- tests/unit/mock/loader.py
bump devel tests to freebsd 13.2
The sanity test 'replace-urlopen' does not test path 'tests/utils/shippable/check_matrix.py', remove this.
> ci: bump devel tests to freebsd 13.2, fix sanity test and linting

- changelogs/fragments/156_fix_windows_encoding.yml
- plugins/connection/libvirt_qemu.py
On Windows guests the default encoding will be set to whatever default legacy encoding, not utf-8. This issue isn't apparent on English locale Windows guests, as there the encodings (ISO-8859-1, utf-8) happen to coincide.
However, on e.g. German Windows guests this will cause an encoding error when reading any output from there.
This patch ensures that the proper encoding is set on every command.
> Fix encoding errors on Windows guests (fixes: #156)

- README.md
- plugins/doc_fragments/requirements.py
fixes #165
lxml seems a requirement, and isn't explicitly stated, and isn't necessarily available by default.
virt
See the linked issue.
```paste below
```
> Add lxml Python dependency to documentation.

- .azure-pipelines/azure-pipelines.yml
- tests/unit/mock/loader.py
- tests/utils/shippable/shippable.sh
Fix linting issues by swapping `type()` with `isinstance()` and ignoring
shellcheck SC2153 rule on `SHIPPABLE_BUILD_DIR`.
RHEL 9.2 has been deprecated from ansible-test and replaced with RHEL
9.3, see
https://forum.ansible.com/t/ansible-test-added-rhel-9-3-and-deprecated-rhel-9-2/2336/1.
Fedora 38 has been deprecated and swapped with 39, see
https://forum.ansible.com/t/ansible-test-added-fedora-39-and-deprecated-fedora-38/2440/1.
FreeBSD 13.1 has been deprecated and swapped with 13.2 in tests for 2.14
and 2.15, see
https://forum.ansible.com/t/ansible-test-ansible-core-2-14-and-2-15-updating-from-freebsd-13-1-to-13-2/2853/2.
Support for Python 2.7 and 3.6 has been dropped, so deprecate images, see
https://github.com/ansible-collections/news-for-maintainers/issues/60#issuecomment-1746173749. …
> fix up CI pipeline

- .azure-pipelines/azure-pipelines.yml
- tests/sanity/ignore-2.18.txt
- tests/unit/compat/mock.py
The devel version of ansible-test has been updated to include support for FreeBSD 13.3, so this change swaps out 13.2 accordingly.
See https://github.com/ansible-collections/news-for-maintainers/issues/67
> ci: replace freebsd 13.2 with 13.3

- .azure-pipelines/azure-pipelines.yml
- tests/sanity/ignore-2.19.txt
With the release of 2.18, devel is now 2.19, so this change adds in support to test 2.19 specifically.
> CI: add support for 2.19

- changelogs/fragments/libvirt_lxc.yml
- plugins/connection/libvirt_lxc.py
* move libvirt_lxc_noseclabel config from base.yml to plugin
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
> libvirt_lxc: Add configuration for libvirt_lxc_noseclabel

- changelogs/fragments/187-add-uuid.yaml
- plugins/doc_fragments/virt.py
- plugins/modules/virt.py
This adds feature as per https://github.com/ansible-collections/community.libvirt/issues/187
TL;DR for some automations, the UUID of the domain is required. This PR adds the ability to get the domain via the ansible module
This is an addition to the plugin `virt.py` which allows the ansible module to make use of the `UUIDString()` already available in the underlying libvirt python module
A simply playbook will demonstrate the UUID:
```
---
- name: get UUID
gather_facts: false
hosts: localhost
tasks:
- name: register vm info
community.libvirt.virt:
command: uuid
name: "my_domain"
register: vminfo
- name: display uuid
debug:
var: vminfo
```
Which will result in the following output
```paste below
ok: [localhost] => {
"vminfo": {
"changed": false,
"failed": false, …
```
> Implement ansible module gathering UUID

- changelogs/fragments/183-check-mode.yml
- plugins/modules/virt.py
- tests/integration/targets/virt/aliases
- tests/integration/targets/virt/defaults/main.yml
- tests/integration/targets/virt/tasks/define_check_mode.yml
- tests/integration/targets/virt/tasks/main.yml
- tests/integration/targets/virt/templates/test_domain.xml.j2
- tests/integration/targets/virt/vars/Debian.yml
- tests/integration/targets/virt/vars/Fedora.yml
- tests/integration/targets/virt/vars/RedHat.yml
- tests/integration/targets/virt/vars/Ubuntu-18.04.yml
- tests/integration/targets/virt/vars/Ubuntu-20.04.yml
- tests/integration/targets/virt/vars/Ubuntu.yml
- tests/integration/targets/virt/vars/default.yml
Implement --check support for the libvirt.virt module
Fixes #98.
virt
Initial implementation to support --check mode.
This adds checking to the Virt class to make check mode calls no-ops but returning valid information where possible. For the get methods this doesn't affect behaviour, but for state changes and for defining domains this will make the Virt class do nothing in check mode.
For defining a new domain, this will pretty-print both XML definitions to make the diff output clean. It's not perfect because libvirt adds additional attributes when defining a domain that are implicit. Those will not change the domain if they are not specified in the input XML.
Tested check mode: define/undefine.
```
TASK [libvirt-domain : Define Domain (domain)] …
```
> Implement --check support for the libvirt.virt module

- changelogs/fragments/177-undefine-disks.yaml
- plugins/modules/virt.py
- tests/integration/targets/virt_undefine/defaults/main.yml
- tests/integration/targets/virt_undefine/files/Dockerfile_Fedora
- tests/integration/targets/virt_undefine/files/Dockerfile_Ubuntu
- tests/integration/targets/virt_undefine/files/vm_template.xml.j2
- tests/integration/targets/virt_undefine/tasks/main.yml
When you undefine a domain currently the volumes are left behind as a manual cleanup task
Fixes #177 and #171 
virt.py has been adjusted to handle a new `delete_volumes` flag
A new `delete_domain_volumes` function is created which does not return anything. It gets the disk objects from the xml by using `self.get_xml`. It then loops over these volumes and using the underlying python function `.delete()` to remove the disk.
The undefine function has been modified slightly to delete the disk if the flag `32` which is the `delete_volumes` flag is detected
```
def undefine(self, vmid, flag):
vm = self.find_vm(vmid)
if flag & 32:
self.delete_domain_volumes(vmid)
return vm.undefineFlags(flag)
```
I'm unsure if this is the best approach, but give the layout of the current …
> implement the removal of volumes when a domain is undefined

- plugins/modules/virt_volume.py
- tests/integration/targets/virt_volume/tasks/main.yml
The examples provided in virt_volume were copied from virt_pool and not relevant to the module.
> fix examples for virt_volume

- changelogs/fragments/212_fix_list_volumes.yml
- plugins/module_utils/constants.py
- plugins/modules/virt_volume.py
Fixes #212
Currently, 'virt_volume' command 'list_volumes' is returning a key 'info' which contains a simple list of several numbers. For someone unfamiliar with the libvirt internals the meaning of these values in 'info' are rather unclear.
This PR takes the list of numbers and returns them in following additional key/value pairs:
- 'Type': type of the volume as string (taken from a map as constant)
- 'Capacity': total size of the volume in bytes as integer
- 'Allocation': current allocated size of the volume in bytes as integer
Sources:
- https://libvirt.org/html/libvirt-libvirt-storage.html#virStorageVolInfo
- https://libvirt.org/html/libvirt-libvirt-storage.html#virStorageVolType
Create a new module_util to hold constants with the future goal to share code more easily between modules. …
> Add virt_volume return key/value pairs for Type, Capacity and Allocation

- plugins/modules/virt.py
- tests/unit/module_utils/test_libvirt.py
- tests/unit/module_utils/test_qemu.py
- tests/unit/module_utils/test_virt_install.py
- tests/unit/modules/test_virt_cloud_instance.py
- tests/unit/modules/test_virt_install.py
This refactoring enables code reuse for class LibvirtConnection and other constants between `virt` and other modules.
- Move LibvirtConnection and other reusable constants to plugins/module_utils/libvirt.py
- Add comprehensive unit tests for the LibvirtConnection class
`virt`
> refactor: Extract common libvirt functionality to module_utils
